// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZF9k48fIts0Uka74WcgJ104GTfZh33GQ',
    appId: '1:404619795390:web:db2d298355041caaef37ef',
    messagingSenderId: '404619795390',
    projectId: 'explore-and-remember',
    authDomain: 'explore-and-remember.firebaseapp.com',
    storageBucket: 'explore-and-remember.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsAwx68u-jI4ZLPL8wpfPhm1vdSvhpJ4',
    appId: '1:404619795390:android:8c40165fa649f01def37ef',
    messagingSenderId: '404619795390',
    projectId: 'explore-and-remember',
    storageBucket: 'explore-and-remember.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmflvpbroqK2-yIOCQsuLaMGVZMMAWCbc',
    appId: '1:404619795390:ios:a3e2c6eb857c97b9ef37ef',
    messagingSenderId: '404619795390',
    projectId: 'explore-and-remember',
    storageBucket: 'explore-and-remember.appspot.com',
    iosBundleId: 'com.example.explorerAndRemember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmflvpbroqK2-yIOCQsuLaMGVZMMAWCbc',
    appId: '1:404619795390:ios:f34cfca19064d732ef37ef',
    messagingSenderId: '404619795390',
    projectId: 'explore-and-remember',
    storageBucket: 'explore-and-remember.appspot.com',
    iosBundleId: 'com.example.explorerAndRemember.RunnerTests',
  );
}
